command:
  - "python"
  - "app.py"

env:
  - name: ENDPOINT_NAME
    valueFrom: database

  - name: MASSIVE_API_BASE_URL
    value: "https://api.massive.com"

  - name: MASSIVE_SECRET_SCOPE
    value: "massive"

  - name: MASSIVE_SECRET_KEY
    value: "api-key"
